services:
  - type: web
    name: tems
    runtime: docker
    repo: https://github.com/dhyllrocoedu-ai/transenfo
    branch: v4.5.0
    dockerfilePath: Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://transenfo-1.onrender.com
      - key: LOG_LEVEL
        value: warning
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: APP_KEY
        generateValue: true
